- build.gradle
> #204: Ensure start scripts and JAR are named correctly

- src/main/antlr/Swift.g4
- src/test/swift/com/sleekbyte/tailor/grammar/StringsAndCharacters.swift
> #202: Update grammar for escaped characters

- src/main/antlr/Swift.g4
- src/test/swift/com/sleekbyte/tailor/grammar/Functions.swift
- src/test/swift/com/sleekbyte/tailor/grammar/Macros.swift
- Fixes #209
- Updated context sensitive keywords list
**Note**: The grammar for macros isn't well documented and it appears you can use more than just build configurations as macro conditionals. I'm assuming that any conditional clause can be put in there for the time being, until I find something more specific.
> #209: Grammar fixes

- src/main/java/com/sleekbyte/tailor/listeners/CommentAnalyzer.java
- src/test/java/com/sleekbyte/tailor/functional/WhitespaceTest.java
- src/test/swift/com/sleekbyte/tailor/functional/WhitespaceTest.swift
> Fix documentation comments whitespace bug

- script/install.ps1
- script/install.sh
- src/main/java/com/sleekbyte/tailor/Tailor.java
> #215: Bump version for 0.2.0 release

- src/main/antlr/Swift.g4
- src/main/java/com/sleekbyte/tailor/Tailor.java
- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/common/Rules.java
- src/main/java/com/sleekbyte/tailor/listeners/CommentAnalyzer.java
- src/main/java/com/sleekbyte/tailor/listeners/CommentWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/listeners/TodoCommentListener.java
- src/main/java/com/sleekbyte/tailor/utils/CommentExtractor.java
- src/test/java/com/sleekbyte/tailor/functional/TodoCommentTest.java
- src/test/swift/com/sleekbyte/tailor/functional/TodoCommentTest.swift
- src/test/swift/com/sleekbyte/tailor/functional/WhitespaceTest.swift
> #68: Enforce TODO comment syntax

- script/install.ps1
- script/install.sh
- src/main/java/com/sleekbyte/tailor/Tailor.java
> #219: Bump version from 0.2.0 to 0.2.1

- README.md
> Add homebrew installation steps

- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/listeners/UpperCamelCaseListener.java
- src/test/java/com/sleekbyte/tailor/functional/TailorConfigurationTest.java
- src/test/java/com/sleekbyte/tailor/functional/UpperCamelCaseTest.java
- src/test/swift/com/sleekbyte/tailor/functional/UpperCamelCaseTest.swift
> #107: Ensure generic parameters are UpperCamelCase

- build.gradle
- src/dist/gems/Gemfile
> #228: Update development dependencies

- build.gradle
> #230: Update ANTLR plugin for Gradle

- README.md
> #213: Update references to Tailor website to use HTTPS

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/listeners/WhitespaceListener.java
- src/test/java/com/sleekbyte/tailor/functional/ClosingBraceLineTest.java
- src/test/java/com/sleekbyte/tailor/functional/OpeningBraceLineTest.java
- src/test/java/com/sleekbyte/tailor/functional/WhitespaceTest.java
- src/test/swift/com/sleekbyte/tailor/functional/WhitespaceTest.swift
> #91: Comma spacing in inheritance clauses and generics

- README.md
> #234: Add CI and rule config explanations to README

- script/install.ps1
- script/install.sh
- src/main/java/com/sleekbyte/tailor/Tailor.java
> #238: Bump version number to 0.2.2

- README.md
- src/main/java/com/sleekbyte/tailor/integration/XcodeIntegrator.java
- src/main/resources/com/sleekbyte/tailor/integration/xcode_integrate.rb
- src/test/java/com/sleekbyte/tailor/integration/XcodeIntegratorTest.java
> #244: Warn if Tailor not installed, extract ruby script

- src/main/java/com/sleekbyte/tailor/listeners/BraceStyleListener.java
- src/test/java/com/sleekbyte/tailor/functional/OpeningBraceLineTest.java
- src/test/swift/com/sleekbyte/tailor/functional/OpeningBraceLineTest.swift
> #249: Fix for willSet and didSet

- src/main/java/com/sleekbyte/tailor/common/Severity.java
- src/main/java/com/sleekbyte/tailor/integration/XcodeIntegrator.java
- src/main/java/com/sleekbyte/tailor/listeners/BraceStyleListener.java
- src/main/java/com/sleekbyte/tailor/listeners/FileListener.java
- src/main/java/com/sleekbyte/tailor/output/Printer.java
- src/main/java/com/sleekbyte/tailor/utils/WhitespaceVerifier.java
- src/test/java/com/sleekbyte/tailor/cli/CliOptionsTest.java
- src/test/java/com/sleekbyte/tailor/functional/CommaWhitespaceTest.java
- src/test/java/com/sleekbyte/tailor/functional/ConstructLengthTest.java
- src/test/java/com/sleekbyte/tailor/functional/NameLengthTest.java
- src/test/java/com/sleekbyte/tailor/grammar/GrammarTest.java
- src/test/java/com/sleekbyte/tailor/integration/XcodeIntegratorTest.java
- src/test/java/com/sleekbyte/tailor/listeners/FileListenerTest.java
- src/test/java/com/sleekbyte/tailor/output/ViolationMessageTest.java
> #255: Address Codacy warnings

- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/common/Rules.java
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/AngleBracketWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/ArrowWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/ColonWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/CommaWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/OperatorWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/ParenthesisWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/utils/WhitespaceVerifier.java
- src/test/java/com/sleekbyte/tailor/functional/AngleBracketWhitespaceTest.java
- src/test/java/com/sleekbyte/tailor/functional/ArrowWhitespaceTest.java
- src/test/java/com/sleekbyte/tailor/functional/ColonWhitespaceTest.java
- src/test/java/com/sleekbyte/tailor/functional/CommaWhitespaceTest.java
- src/test/java/com/sleekbyte/tailor/functional/ForceCastTest.java
- src/test/java/com/sleekbyte/tailor/functional/LowerCamelCaseTest.java
- src/test/java/com/sleekbyte/tailor/functional/MaxNameLengthTest.java
- src/test/java/com/sleekbyte/tailor/functional/MinNameLengthTest.java
- src/test/java/com/sleekbyte/tailor/functional/ParenthesisWhitespaceTest.java
- src/test/java/com/sleekbyte/tailor/functional/SortedPrinterOutputTest.java
- src/test/java/com/sleekbyte/tailor/functional/TailorConfigurationTest.java
- src/test/java/com/sleekbyte/tailor/functional/UpperCamelCaseTest.java
- src/test/swift/com/sleekbyte/tailor/functional/AngleBracketWhitespaceTest.swift
- src/test/swift/com/sleekbyte/tailor/functional/ParenthesisWhitespaceTest.swift
> #87: Flag redundant whitespace in and around < > & ( ) 

- README.md
> #261: Update README

- README.md
> #265: Update description

- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/AngleBracketWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/ParenthesisWhitespaceListener.java
- src/main/java/com/sleekbyte/tailor/utils/WhitespaceVerifier.java
- src/test/java/com/sleekbyte/tailor/functional/AngleBracketWhitespaceTest.java
- src/test/java/com/sleekbyte/tailor/functional/ParenthesisWhitespaceTest.java
- src/test/swift/com/sleekbyte/tailor/functional/AngleBracketWhitespaceTest.swift
- src/test/swift/com/sleekbyte/tailor/functional/ParenthesisWhitespaceTest.swift
> #267: Add ( ) and < > whitespace check for operator overloading functions

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/CommaWhitespaceListener.java
- src/test/java/com/sleekbyte/tailor/functional/CommaWhitespaceTest.java
- src/test/swift/com/sleekbyte/tailor/functional/CommaWhitespaceTest.swift
> #240: Comma whitespace checks #1

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/CommaWhitespaceListener.java
- src/test/java/com/sleekbyte/tailor/functional/CommaWhitespaceTest.java
- src/test/swift/com/sleekbyte/tailor/functional/CommaWhitespaceTest.swift
Addresses #240.
- generic argument list
- pattern initializer list
- parameter list
- enum case lists (raw and union)
> #240: Comma whitespace checks #2

- build.gradle
- script/install.ps1
- script/install.sh
- script/uninstall.ps1
- src/main/resources/config.properties
> #283: Bump version number to v0.4.0

- .gitignore
- README.md
- build.gradle
- man/Gemfile
- man/tailor.1.ronn
- script/bootstrap
* Add Bundler to developer requirements and `script/bootstrap`
* Resolves #142
> #142: Add Tailor man page

- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/common/Rules.java
- src/main/java/com/sleekbyte/tailor/listeners/OptionalBindingListener.java
- src/test/java/com/sleekbyte/tailor/functional/RedundantOptionalBindingTest.java
- src/test/swift/com/sleekbyte/tailor/functional/RedundantOptionalBindingTest.swift
> #289: Flag redundant `let/var` in optional binding

- build.gradle
- script/install.sh
- script/uninstall.sh
> #292: Fix installation with man page

- config/pmd/tailorRuleSet.xml
- src/main/java/com/sleekbyte/tailor/Tailor.java
- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/format/Formatter.java
- src/main/java/com/sleekbyte/tailor/format/XcodeFormatter.java
- src/main/java/com/sleekbyte/tailor/output/Printer.java
- src/main/java/com/sleekbyte/tailor/output/ViolationMessage.java
- src/test/java/com/sleekbyte/tailor/format/XcodeFormatterTest.java
- src/test/java/com/sleekbyte/tailor/listeners/FileListenerTest.java
- src/test/java/com/sleekbyte/tailor/output/PrinterTest.java
- src/test/java/com/sleekbyte/tailor/output/ViolationMessageTest.java
> #298: Extract output formatting code to XcodeFormatter

- src/main/java/com/sleekbyte/tailor/listeners/LowerCamelCaseListener.java
- src/main/java/com/sleekbyte/tailor/utils/CharFormatUtil.java
- src/test/java/com/sleekbyte/tailor/functional/LowerCamelCaseTest.java
- src/test/java/com/sleekbyte/tailor/utils/CharFormatUtilTest.java
- src/test/swift/com/sleekbyte/tailor/functional/LowerCamelCaseTest.swift
> #305: Relax lowerCamelCase rule for acronyms

- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/common/Rules.java
- src/main/java/com/sleekbyte/tailor/listeners/TrailingClosureListener.java
- src/test/java/com/sleekbyte/tailor/functional/TrailingClosureTest.java
- src/test/swift/com/sleekbyte/tailor/functional/TrailingClosureTest.swift
> #307: Implement trailing closure rule

- .travis.yml
- README.md
- build.gradle
> #311: Use Coveralls for test coverage

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/test/swift/com/sleekbyte/tailor/grammar/LineComment.swift
> #315: Single line comments can terminate with EOF

- build.gradle
> #321: Update ANTLR to v4.5.2-1

- .travis.yml
Attempt to automate releases via Travis CI.
Addresses #328.
> #328: Travis Releases

- .travis.yml
- README.md
- build.gradle
- script/bootstrap
> #328: Complete Travis Releases setup

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/test/swift/com/sleekbyte/tailor/grammar/StringsAndCharacters.swift
> #278: Add grammar rules for string interpolation

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/test/swift/com/sleekbyte/tailor/grammar/AdvancedOperators.swift
- src/test/swift/com/sleekbyte/tailor/grammar/Extensions.swift
- src/test/swift/com/sleekbyte/tailor/grammar/OptionalChaining.swift
> #343: Fix some grammar issues

- src/main/java/com/sleekbyte/tailor/Tailor.java
- src/main/java/com/sleekbyte/tailor/utils/Configuration.java
> #349: Fix handling of CLIArgumentParserException

- README.md
- src/main/java/com/sleekbyte/tailor/common/Messages.java
- src/main/java/com/sleekbyte/tailor/common/Rules.java
- src/main/java/com/sleekbyte/tailor/common/YamlConfiguration.java
- src/main/java/com/sleekbyte/tailor/utils/CLIArgumentParser.java
- src/main/java/com/sleekbyte/tailor/utils/CharFormatUtil.java
- src/main/java/com/sleekbyte/tailor/utils/Configuration.java
- src/test/java/com/sleekbyte/tailor/functional/FormatTest.java
- src/test/java/com/sleekbyte/tailor/functional/yaml/YamlConfigurationTest.java
> #340: Configuration File Extension

- src/main/java/com/sleekbyte/tailor/listeners/TodoCommentListener.java
- src/test/java/com/sleekbyte/tailor/functional/TodoCommentTest.java
- src/test/swift/com/sleekbyte/tailor/functional/TodoCommentTest.swift
> #355: Only flag comments with TODO as independent word

- src/main/resources/com/sleekbyte/tailor/common/brace-style.md
- src/main/resources/com/sleekbyte/tailor/common/colon-whitespace.md
- src/main/resources/com/sleekbyte/tailor/common/lower-camel-case.md
- src/main/resources/com/sleekbyte/tailor/common/redundant-parentheses.md
- src/main/resources/com/sleekbyte/tailor/common/upper-camel-case.md
> #371: Remove anchor links from rule examples

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/test/swift/com/sleekbyte/tailor/grammar/StringsAndCharacters.swift
> #356: Modify string interpolation lexer rule

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/test/swift/com/sleekbyte/tailor/grammar/Extensions.swift
- src/test/swift/com/sleekbyte/tailor/grammar/Functions.swift
- src/test/swift/com/sleekbyte/tailor/grammar/Protocols.swift
- src/test/swift/com/sleekbyte/tailor/grammar/StringsAndCharacters.swift
> #385: Grammar fixes

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/main/java/com/sleekbyte/tailor/listeners/ConstantDecHelper.java
> #387: Optimize some rules

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
> #391: Add Developer Certificate of Origin

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/test/swift/com/sleekbyte/tailor/grammar/ClassesAndStructures.swift
> #393: Allow modifiers before getterClause/setterClause

- src/main/java/com/sleekbyte/tailor/listeners/TrailingClosureListener.java
- src/test/java/com/sleekbyte/tailor/functional/TrailingClosureTest.java
- src/test/swift/com/sleekbyte/tailor/functional/TrailingClosureTest.swift
> #401: Disable trailing closure check inside condition clauses

- build.gradle
> #410: Upgrade ANTLR to 4.5.3

- src/test/java/com/sleekbyte/tailor/functional/ParseFailureTest.java
- src/test/swift/com/sleekbyte/tailor/functional/ParseFailureTest.swift
> #416: Test an invalid Swift file

- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/main/java/com/sleekbyte/tailor/listeners/whitespace/ColonWhitespaceListener.java
- src/test/java/com/sleekbyte/tailor/functional/ColonWhitespaceTest.java
- src/test/swift/com/sleekbyte/tailor/functional/ColonWhitespaceTest.swift
- src/test/swift/com/sleekbyte/tailor/grammar/ControlFlow.swift
> #425: Fix expressionElement grammar issue

- .travis.yml
- build.gradle
- src/dist/gems/Gemfile
> #430: Update dependencies

- build.gradle
- src/dist/gems/Gemfile
> #440: Update dependencies

- build.gradle
- src/main/java/com/sleekbyte/tailor/listeners/LowerCamelCaseListener.java
- src/main/java/com/sleekbyte/tailor/listeners/UpperCamelCaseListener.java
- src/test/java/com/sleekbyte/tailor/common/ConfigPropertiesTest.java
- src/test/java/com/sleekbyte/tailor/functional/FormatTest.java
- src/test/java/com/sleekbyte/tailor/functional/LowerCamelCaseTest.java
- src/test/java/com/sleekbyte/tailor/functional/SemicolonTest.java
- src/test/java/com/sleekbyte/tailor/functional/UpperCamelCaseTest.java
- src/test/java/com/sleekbyte/tailor/utils/SourceFileUtilTest.java
- src/test/swift/com/sleekbyte/tailor/functional/LowerCamelCaseTest.swift
- src/test/swift/com/sleekbyte/tailor/functional/SortedPrinterOutputTest.swift
- src/test/swift/com/sleekbyte/tailor/functional/UpperCamelCaseTest.swift
> #453: Enforce lowercamelcase naming on Enumeration Cases

- build.gradle
- src/main/antlr/com/sleekbyte/tailor/antlr/Swift.g4
- src/main/java/com/sleekbyte/tailor/listeners/LowerCamelCaseListener.java
- src/main/java/com/sleekbyte/tailor/listeners/UpperCamelCaseListener.java
- src/test/java/com/sleekbyte/tailor/common/ConfigPropertiesTest.java
- src/test/java/com/sleekbyte/tailor/functional/FormatTest.java
- src/test/java/com/sleekbyte/tailor/functional/LowerCamelCaseTest.java
- src/test/java/com/sleekbyte/tailor/functional/SemicolonTest.java
- src/test/java/com/sleekbyte/tailor/functional/UpperCamelCaseTest.java
- src/test/java/com/sleekbyte/tailor/utils/SourceFileUtilTest.java
- src/test/swift/com/sleekbyte/tailor/functional/LowerCamelCaseTest.swift
- src/test/swift/com/sleekbyte/tailor/functional/SortedPrinterOutputTest.swift
- src/test/swift/com/sleekbyte/tailor/functional/UpperCamelCaseTest.swift
- src/test/swift/com/sleekbyte/tailor/grammar/AccessControl.swift
- src/test/swift/com/sleekbyte/tailor/grammar/ErrorHandling.swift
Pull Request branch is based on `at-453-enum-case-lower-camel-case-bugfix`.
Resolves #452.
> #452: Add new Swift 3.0 access modifiers to the grammar

- build.gradle
> #456: Update dependencies

- build.gradle
- src/dist/gems/Gemfile
> #466: Update dependencies

- README.md
> #464: Configure Xcode to Run Tailor in Analyze Phase

- build.gradle
> #478: Update dependencies
